networks:
  osb-internal:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: opensimplebank
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opensimplebank
    ports:
      - 6969:5432
    volumes:
      - ./live/pgdata:/var/lib/postgresql/data
    networks:
      - osb-internal
  app:
    build: .
    restart: unless-stopped
    ports:
      - 3030:80
    networks:
      - osb-internal